name: telehealth_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get: ^4.6.6
  provider: ^6.1.2
  gap: ^3.0.1
  google_fonts: ^6.2.1
  device_preview: ^1.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  file_picker: ^10.3.3
  image_picker:
  firebase_core:



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/


